### ISSUE TITLE
Rough Todo List

### ISSUE THREAD

**Issue by e-schultz** [e-schultz/ts-js-react-training#14]
# Day 1 - JavaScript Basics

- [ ] Variable Declarations
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Template literals
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Objects & Spread
  - [x] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Functions Paramaters
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Function Context / Scope / This
  - [x] Content
  - [x] Examples
  - [x] Exercise if Applicable
- [ ] Functions Returns
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Arrow Functions
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Function Callbacks / Functions Returning Functions
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Array & Array Methods
  - [x] Content
  - [x] Examples
  - [ ] Exercise if Applicable
- [ ] Classes
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable

## Day 2 - JS & TypeScript

- [ ] How Does TypeScript Work
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Interfaces
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Type Inference
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [x] Promises
  - [x] Content
  - [x] Examples
  - [x] Exercise if Applicable
- [ ] Async Await
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] API Requests
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable

## Day 3 - React Fundamentals

- [ ] Intro to Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] JSX
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Props & Attributes
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Styling Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Set State
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Handling Events
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Inputs & Forms
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Component State
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Class Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Lifecycle Methods/Hooks
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable

## Day 3 - Intermediate React

- [ ] Intro to React Architecture
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Composing Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Testing React Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Higher Order Components - probably drop / skim over
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Render Prop Components
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Integrating React & Dojo
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable
- [ ] Understanding The Virtual DOM
  - [ ] Content
  - [ ] Examples
  - [ ] Exercise if Applicable

## Day 4 + 5

- [ ] Onsite Support
- [ ] ad-hoc mini workshops
- [ ] Mentorship and guidance
